### ISSUE TITLE
E-mail addresses

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#26] opened 2016-02-11 09:08 UTC
Need to figure out if there's a way to return the e-mail addresses from Slack login, so that we can import them into a newsletter or use for future transactional notifications (e.g. event reminders).

**Comment by sheldonbarnes** [comment] 2016-02-29 21:14
According to the docs, the users.info method contains an email address:

https://api.slack.com/methods/users.info

{
    "ok": true,
    "user": {
        "id": "U023BECGF",
        "name": "bobby",
        "deleted": false,
        "color": "9f69e7",
        "profile": {
            "first_name": "Bobby",
            "last_name": "Tables",
            "real_name": "Bobby Tables",
            "email": "bobby@slack.com",
            "skype": "my-skype-name",
            "phone": "+1 (123) 456 7890",
            "image_24": "https:\/\/...",
            "image_32": "https:\/\/...",
            "image_48": "https:\/\/...",
            "image_72": "https:\/\/...",
            "image_192": "https:\/\/..."
        },
        "is_admin": true,
        "is_owner": true,
        "has_2fa": true,
        "has_files": true
    }
}

I would love to contribute if I can with your help @lpatmo

**Comment by sgtquezada** [comment] 2016-02-29 21:49
@sheldonbarnes I would probably need this functionality since we may go down the path of notifying users via email if a hangout has been cancelled (deleted) for issue #40 

Let me know if you need help or plan to work on it!

**Comment by sgtquezada** [comment] 2016-02-29 22:54
Nevermind. I looked at the users collection in mongo and it appears the email address is already being captured as part of the slack user's identity (from the users.info API method call). It's stored under the user_info.profile property. I would need to do a quick test to see I can pull it out and store it somewhere just to make sure!

If so - I think we can close this issue.

**Comment by sheldonbarnes** [comment] 2016-02-29 22:55
Ok, cool.  I'll look at another feature I can help with.

~Sheldon

**Comment by sgtquezada** [comment] 2016-02-29 23:56
ok confirmed. I am able to see and pull the user's email addy! we can close this issue!

**Closed** 2016-03-01 01:13 UTC
Labels: enhancement, help wanted, question
