### ISSUE TITLE
Slack alerts not appearing for scheduled hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#339] opened 2016-10-16 03:00 UTC
@distalx found the bug -- something in `server/slack/methods.js`.

**Comment by distalx** [comment] 2016-10-16 03:20
Right now alert for newly created hangout is not being posted to slack channels, maybe because of following code block.
```
if(minutes > 0)
{
    hangoutAlert(data)
}
```

@lpatmo I believe @abhiii5459  is already working on this feature, #326 . @abhiii5459 would you mind take a look at it ?

**Comment by abhiii5459** [comment] 2016-10-16 04:01
@distalx @lpatmo I'll check it out today!

**Comment by lpatmo** [comment] 2016-10-17 03:16
In the `issue-193-make-hangout-start/end-time-optional` branch, I was just able to get new Slack alerts appearing in #cb2-test *as long as* I changed the start time. May be a clue.

**Comment by abhiii5459** [comment] 2016-10-17 03:20
@lpatmo  Then I think I have that covered in #338  :) PR has been raised! Can you please check?

**Comment by lpatmo** [comment] 2016-10-17 08:00
Looks good! The only remaining bug I see happens when I create a hangout now and don’t change the start time. If I increase the start time by even a minute, the Slack notification is successful.

**Comment by abhiii5459** [comment] 2016-10-17 22:53
Let me see if even that last nail in the coffin can be addressed

**Comment by sergeant-q** [comment] 2016-10-26 06:50
I am not sure if this bug exists in the `master` branch because I am unable to reproduce this issue. (I am working in the master branch). Can someone confirm what branch should we be testing the Slack alerts not firing off for new hangouts?

**Comment by lpatmo** [comment] 2016-10-26 06:52
@sergeant-q I see this in the `master` branch. If you schedule a hangout in advance, the alerts should appear... but not if you don't change the start time when you first click to create the hangout.

**Comment by sergeant-q** [comment] 2016-10-26 15:52
@abhiii5459 I have a fix for this. Please take a look at it and let me know if you're good to go with it.

**Comment by abhiii5459** [comment] 2016-10-27 01:42
@sergeant-q Checking.

**Closed** 2016-10-29 16:38 UTC
Labels: bug, claimed, Hacktoberfest, in progress
