### ISSUE TITLE
Write a Hangouts FAQ

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#22] opened 2016-02-02 05:46 UTC
There should be a "Hangouts FAQ" link on the home page, and it'll open up a pop up that explains all the different types of hangouts: silent, pair, collaborative. 

And includes a screenshot of what one might expect.

And then *stresses* that people don't need to turn on their cameras or microphones.

**Comment by wuworkshop** [comment] 2016-02-03 09:44
Isn't this a duplicate of https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/10?

**Closed** 2016-04-07 02:29 UTC
